# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{yamo}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kenneth Vestergaard Schmidt"]
  s.date = %q{2009-12-03}
  s.description = %q{Classes for loading schema-validated YAML, and creating nice Ruby-objects with accessors}
  s.email = %q{kvs@binarysolutions.dk}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/yamo.rb",
     "lib/yamo/collection.rb",
     "lib/yamo/object.rb",
     "lib/yamo/singleton.rb",
     "lib/yamo/validator.rb",
     "test/data/collection/obj1",
     "test/data/collection/obj2",
     "test/data/collection_bogus/obj1",
     "test/data/collection_bogus/obj2",
     "test/data/schemas/collection.yaml",
     "test/data/schemas/collection_bogus.yaml",
     "test/data/schemas/singleton.yaml",
     "test/data/singleton.conf",
     "test/helper.rb",
     "test/test_collection.rb",
     "test/test_singleton.rb",
     "test/test_validation.rb"
  ]
  s.homepage = %q{http://github.com/kvs/yamo}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{YAML Model Objects}
  s.test_files = [
    "test/helper.rb",
     "test/test_collection.rb",
     "test/test_singleton.rb",
     "test/test_validation.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

